# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

config.vm.define "server" do |server|
  config.vm.box = 'centos/8.2'
  config.vm.box_url = 'https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-Vagrant-8.2.2004-20200611.2.x86_64.vagrant-virtualbox.box'

  server.vm.host_name = 'server'
  server.vm.network :private_network, ip: "10.0.0.41"

  server.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  server.vm.provision "shell",
    name: "Setup nfs server",
    path: "setup_nfs_serv.sh"
	
  end

  config.vm.define "client" do |client|
    client.vm.box = 'centos/8.2'
    client.vm.host_name = 'client'
    client.vm.network :private_network, ip: "10.0.0.40"
    client.vm.provider :virtualbox do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
	
	client.vm.provision "shell",
		name: "Setup nfs client",
		path: "setup_nfs_client.sh"
	
  end

end
